name: Node.js CI

on:
  push:
    branches: [ main, master, Dev ]
  pull_request:
    branches: [ main, master, Dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then npm ci; else npm install; fi
